#!/usr/bin/env python3
"""Post-process the extracted GENE-LINK message folders:
 1. decode RFC2047 encoded-words + unfold folded headers in the DISPLAY fields of
    EMAIL.md (the verbatim "Raw message headers" block is left untouched);
 2. build ALL_EMAILS.txt - every message's details + body in one file;
 3. report folder names that had to be truncated.
"""
import csv
import email.header
import os
import re

DST = "/home/pro-g/Downloads/gene-link/RFP Submissions/GL RFP Applications - Extracted"


def decode_names(value):
    """Decode =?UTF-8?B?...?= words, keep the address part as-is."""
    if not value or value == "(none)":
        return value
    try:
        out = str(email.header.make_header(email.header.decode_header(value)))
    except Exception:
        return value
    return out


def unfold(value):
    """Collapse RFC5322 header folding (\r\n + indent) into single spaces."""
    return re.sub(r"\r?\n[ \t]+", " ", str(value)).strip()


def fix_email_md(path):
    raw = open(path, encoding="utf-8").read()
    head, sep, tail = raw.partition("## Raw message headers")
    def repl(m):
        field, val = m.group(1), m.group(2)
        # join continuation lines belonging to this field
        return f"- **{field}:** {decode_names(unfold(val))}"
    head = re.sub(r"- \*\*(To|Cc|Bcc|From \(name\)|Reply-To):\*\*([^\n]*(?:\n(?![-\n#]).*)*)",
                  repl, head)
    open(path, "w", encoding="utf-8").write(head + sep + tail)


rows = list(csv.DictReader(open(os.path.join(DST, "index.csv"))))
for r in rows:
    fix_email_md(os.path.join(DST, r["folder"], "EMAIL.md"))

# combined text file
lines = ["GENE-LINK RFP (GL RFP 260903) - ALL SUBMITTED MESSAGES",
         "=" * 78,
         f"{len(rows)} messages. Source: GL RFP Applications (.msg files).",
         "Generated by Hermes from the original Outlook .msg files.",
         ""]
for i, r in enumerate(rows, 1):
    p = os.path.join(DST, r["folder"])
    body = open(os.path.join(p, "EMAIL_BODY.txt"), encoding="utf-8").read().strip()
    lines += ["=" * 78,
              f"[{i:02d}] {r['subject']}",
              "-" * 78,
              f"Date      : {r['date']}",
              f"From      : {r['from_name']} <{r['from_email']}>",
              f"To        : {unfold(r['to'])}",
              f"Cc        : {unfold(r['cc']) if r['cc'] else '(none)'}",
              f"Message-ID: {open(os.path.join(p,'EMAIL.md'),encoding='utf-8').read().split('**Message-ID:** ')[1].split(chr(10))[0] if '**Message-ID:** ' in open(os.path.join(p,'EMAIL.md'),encoding='utf-8').read() else '(none)'}",
              f"Folder    : {r['folder']}",
              f"Attachments ({r['attachments']}):"]
    for n in (r["attachment_names"].split(" | ") if r["attachment_names"] else ["(none)"]):
        lines.append(f"            - {n}")
    lines += ["", "--- MESSAGE BODY ---", body, ""]
open(os.path.join(DST, "ALL_EMAILS.txt"), "w", encoding="utf-8").write("\n".join(lines))

trunc = [r for r in rows if len(r["subject"]) > 110]
print(f"post-processed {len(rows)} EMAIL.md files; wrote ALL_EMAILS.txt ({os.path.getsize(os.path.join(DST,'ALL_EMAILS.txt')):,} bytes)")
print("folders whose name was truncated:", [(r['folder'][:45], len(r['subject'])) for r in trunc])
